services:
  # Server模块
  xiaozhi-esp32-server:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: xiaozhi-esp32-server
    depends_on:
      xiaozhi-esp32-server-db:
        condition: service_healthy
      xiaozhi-esp32-server-redis:
        condition: service_healthy
      xiaozhi-esp32-server-web:
        condition: service_started
    restart: always
    networks:
      - default
    ports:
      # ws server
      - "8000:8000"
      # The port of the http service, used for visual analysis interface
      - "8003:8003"
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Europe/Paris
    volumes:
      # Configuration file directory
      - ./data:/opt/xiaozhi-esp32-server/data

  # manager-api和manager-web模块
  xiaozhi-esp32-server-web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: xiaozhi-esp32-server-web
    restart: always
    networks:
      - default
    depends_on:
      xiaozhi-esp32-server-db:
        condition: service_healthy
      xiaozhi-esp32-server-redis:
        condition: service_healthy
    ports:
      # 智控台
      - "8002:8002"
    environment:
      - TZ=Europe/Paris
      - SPRING_DATASOURCE_DRUID_URL=${SPRING_DATASOURCE_DRUID_URL:-jdbc:mysql://xiaozhi-esp32-server-db:3306/xiaozhi_esp32_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Paris&nullCatalogMeansCurrent=true&connectTimeout=30000&socketTimeout=30000&autoReconnect=true&failOverReadOnly=false&maxReconnects=10}
      - SPRING_DATASOURCE_DRUID_USERNAME=${MYSQL_ROOT_USERNAME:-root}
      - SPRING_DATASOURCE_DRUID_PASSWORD=${MYSQL_ROOT_PASSWORD:-123456}
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST:-xiaozhi-esp32-server-redis}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT:-6379}
    volumes:
      # 配置文件目录
      - ./uploadfile:/uploadfile

  # 数据库模块
  xiaozhi-esp32-server-db:
    image: mysql:latest
    container_name: xiaozhi-esp32-server-db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    networks:
      - default
    expose:
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-123456}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-xiaozhi_esp32_server}
      - MYSQL_INITDB_ARGS="--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
  # redis模块
  xiaozhi-esp32-server-redis:
    image: redis
    expose:
      - 6379
    container_name: xiaozhi-esp32-server-redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - default
networks:
  default:
